name: rm action

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Số ngày lưu giữ lịch sử các lần chạy (cũ hơn sẽ bị xoá).'
        required: true
        default: '7'
      keep_minimum_runs:
        description: 'Số lần chạy tối thiểu muốn giữ lại.'
        required: true
        default: '5'

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Xoá các lần chạy cũ
        uses: matt-ball/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.keep_minimum_runs }}